name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to Hugging Face
      uses: peaceiris/actions-huggingface@v2
      with:
        hf_token: ${{ secrets.BahishtiZawer }}
        hf_repo: "FaizanArif/Bahishti_Zewar_RAG"
        publishing_dir: "./"
        repository_visibility: "public"
        keep_history: true
      
