name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.BAHISHTIZAWER }}
        run: |
          echo -e "[user]\nemail = faizanarif1884@gmail.com\nname = FaizanArif" > ~/.gitconfig
          git config --global credential.helper store
          echo "https://FaizanArif:${HF_TOKEN}@huggingface.co" > ~/.git-credentials
      
      - name: Pull Git LFS files
        run: |
          git lfs install
          git lfs pull
          
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.BAHISHTIZAWER }}
        run: |
          git remote add space https://huggingface.co/spaces/FaizanArif/Bahishti_Zewar_RAG
          git push space main --force
